#!/bin/bash

PYNAME=runGen.py
wget https://raw.githubusercontent.com/zhaoyuyoung/files/main/$PYNAME

if command -v python &> /dev/null
then
    PY_COMMAND=python
else
    if command -v python3 &> /dev/null
    then
        PY_COMMAND=python3
    else
        PY_COMMAND=python2
    fi
    mkdir tmp_bin
    ln -fs `which $PY_COMMAND` tmp_bin/python
    export PATH=$PWD/tmp_bin:$PATH
fi

echo using $PY_COMMAND

exec python -u $PYNAME "$@"
