name: update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '3 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: 🍳 Shake & bake README
        run: |
          cd ${GITHUB_WORKSPACE}/update/
          go env -w GOFLAGS=-mod=mod
          go run main.go
          cd ${GITHUB_WORKSPACE}


